apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ac-tomcat
  name: ac-tomcat
  namespace: skaha-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ac-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ac-tomcat
    spec:
      containers:
      - name: ac-tomcat
        image: canfar-registry.cloud.computecanada.ca/ac:0.1
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 91
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.ssl/
          name: servops-cert
          readOnly: true
        - mountPath: /root/
          name: db-config
          readOnly: true
        - mountPath: "/root/config"
          name: config-volume
        - mountPath: "/config"
          name: tomcat-config-volume
      volumes:
      - name: servops-cert
        secret:
          defaultMode: 420
          secretName: cavern-servops-secret
      - name: config-volume
        configMap:
          name: ac-config
      - name: tomcat-config-volume
        configMap:
          name: ac-tomcat-config
      - name: db-config
        secret:
          defaultMode: 420
          secretName: ac-dbrc
