apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: arcade-tomcat
  name: arcade-tomcat
  namespace: skaha-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: arcade-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: arcade-tomcat
    spec:
      containers:
      - env:
        - name: arcade.hostname
          value: proto.canfar.net
        - name: arcade.homedir
          value: /cavern
        - name: arcade.namespace
          value: skaha-workload
        image: canfar-registry.cloud.computecanada.ca/arcade-tomcat:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        name: arcade-tomcat
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: "/config"
          name: config-volume
        - mountPath: /root/.ssl/
          name: servops-cert
          readOnly: true
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: cavern
      securityContext:
        runAsUser: 0
      serviceAccountName: skaha
      volumes:
      - name: config-volume
        configMap:
          name: arcade-config
      - name: servops-cert
        secret:
          defaultMode: 420
          secretName: arcade-servops-secret
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false
