---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "carta-session"
    canfar-net-sessionName: "carta-session"
    canfar-net-type: carta
    canfar-net-userid: "cadcauthtest1"
  name: "carta-job"
spec:
  template:
    metadata:
      labels:
        canfar-net-sessionID: "carta-session"
        canfar-net-sessionName: "carta-session"
        canfar-net-type: carta
        canfar-net-userid: "cadcauthtest1"
        job-name: "carta-job"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      initContainers:
      - name: init-sssd-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - mkdir -p /var/lib/sss/pipes/private;
          chmod 700 /var/lib/sss/pipes/private;
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      containers:
      - name: "carta-container"
        env:
        - name: arcade_hostname
          value: "proto.canfar.net"
        - name: arcade_username
          value: "cadcauthtest1"
        securityContext:
          runAsUser: 20004
          runAsGroup: 20004
        image: canfar-registry.cloud.computecanada.ca/arcade-carta:latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        #imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
        - /carta/arcade-carta /cavern /cavern/projects
        ports:
        - containerPort: 5901
          protocol: TCP
          name: vnc-port
        - containerPort: 6901
          protocol: TCP
          name: novnc-port
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      - name: cavern-sssd
        image: canfar-registry.cloud.computecanada.ca/cadc-sssd:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sssd/sssd.conf
          subPath: sssd.conf
          name: sssd-config-vol
        - mountPath: /etc/openldap/certs/ca.crt
          subPath: ca.crt
          name: sssd-cert-config-vol
        - mountPath: /etc/openldap/certs/cadc_CA_2029.crt
          subPath: cadc_CA_2029.crt
          name: sssd-cert-config-vol
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      volumes:
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim
      - name: sssd-config-vol
        configMap:
          name: sssd-config
          # defaultMode of 256 sets the permissions of the file
          # to 0400 - needed by sssd
          defaultMode: 256
      - name: sssd-cert-config-vol
        configMap:
          name: sssd-cert-config
      - name: sssd-dir
        emptyDir: {}
