---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${arcade.sessionid}"
    canfar-net-sessionName: "${arcade.sessionname}"
    canfar-net-sessionType: "${arcade.sessiontype}"
    canfar-net-userid: "${arcade.userid}"
  name: "${arcade.podname}"
spec:
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${arcade.sessionid}"
        canfar-net-sessionName: "${arcade.sessionname}"
        canfar-net-sessionType: "${arcade.sessiontype}"
        canfar-net-userid: "${arcade.userid}"
        job-name: "${arcade.podname}"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      initContainers:
      - name: init-sssd-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - mkdir -p /var/lib/sss/pipes/private;
          chmod 700 /var/lib/sss/pipes/private;
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      containers:
      - name: "${arcade.podname}"
        env:
        - name: VNC_PW
          value: "${arcade.sessionid}"
        - name: arcade_hostname
          value: "${arcade.hostname}"
        - name: arcade_username
          value: "${arcade.userid}"
        securityContext:
          runAsUser: ${arcade.posixid} 
          runAsGroup: ${arcade.posixid}
        image: canfar-registry.cloud.computecanada.ca/arcade-desktop:latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        #imagePullPolicy: Never
        ports:
        - containerPort: 5901
          protocol: TCP
          name: vnc-port
        - containerPort: 6901
          protocol: TCP
          name: novnc-port
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      - name: cavern-sssd
        image: canfar-registry.cloud.computecanada.ca/cadc-sssd:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sssd/sssd.conf
          subPath: sssd.conf
          name: sssd-config-vol
        - mountPath: /etc/openldap/certs/ca.crt
          subPath: ca.crt
          name: sssd-cert-config-vol
        - mountPath: /etc/openldap/certs/cadc_CA_2029.crt
          subPath: cadc_CA_2029.crt
          name: sssd-cert-config-vol
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      volumes:
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim
      - name: sssd-config-vol
        configMap:
          name: sssd-config
          # defaultMode of 256 sets the permissions of the file
          # to 0400 - needed by sssd
          defaultMode: 256
      - name: sssd-cert-config-vol
        configMap:
          name: sssd-cert-config
      - name: sssd-dir
        emptyDir: {}
