---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${arcade.sessionid}"
    canfar-net-sessionName: "${arcade.sessionname}"
    canfar-net-sessionType: "${arcade.sessiontype}"
    canfar-net-userid: "${arcade.userid}"
  name: "${arcade.jobname}"
spec:
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${arcade.sessionid}"
        canfar-net-sessionName: "${arcade.sessionname}"
        canfar-net-sessionType: "${arcade.sessiontype}"
        canfar-net-userid: "${arcade.userid}"
        job-name: "${arcade.jobname}"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      containers:
      - name: "${arcade.jobname}"
        env:
        - name: arcade_hostname
          value: "${arcade.hostname}"
        - name: arcade_username
          value: "${arcade.userid}"
        securityContext:
          runAsUser: ${arcade.posixid} 
          runAsGroup: ${arcade.posixid}
        image: canfar-registry.cloud.computecanada.ca/arcade-carta:latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        #imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
        - /carta/arcade-carta /cavern /cavern/projects
        ports:
        - containerPort: 5901
          protocol: TCP
          name: websocket-port
        - containerPort: 6901
          protocol: TCP
          name: frontend-port
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${arcade.sessionid}"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false
     - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
