apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cavern-tomcat
  name: cavern-tomcat
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cavern-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cavern-tomcat
    spec:
      initContainers:
      - name: init-sssd-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - mkdir /var/lib/sss/pipes/private;
          chmod 700 /var/lib/sss/pipes/private;
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      containers:
      - name: cavern-tomcat
        image: canfar-registry.cloud.computecanada.ca/cavern-tomcat:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.ssl/
          name: servops-cert
          readOnly: true
        - mountPath: "/cephfs"
          name: cavern-ceph-volume
        - mountPath: "/config"
          name: config-volume
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      - name: cavern-sssd
        image: canfar-registry.cloud.computecanada.ca/cadc-sssd:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sssd/sssd.conf
          subPath: sssd.conf
          name: sssd-config-vol
        - mountPath: /etc/openldap/certs/ca.crt
          subPath: ca.crt
          name: sssd-cert-config-vol
        - mountPath: /etc/openldap/certs/cadc_CA_2029.crt
          subPath: cadc_CA_2029.crt
          name: sssd-cert-config-vol
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      volumes:
      - name: servops-cert
        secret:
          defaultMode: 420
          secretName: cavern-servops-secret
      - name: cavern-ceph-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim-20200608
      - name: config-volume
        configMap:
          name: cavern-config
      - name: sssd-config-vol
        configMap:
          name: sssd-config
          # defaultMode of 256 sets the permissions of the file
          # to 0400 - needed by sssd
          defaultMode: 256
      - name: sssd-cert-config-vol
        configMap:
          name: sssd-cert-config
      - name: sssd-dir
        emptyDir: {}
