---
apiVersion: batch/v1
kind: Job
metadata:
  name: "arcade-allocate"
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: init-sssd-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - mkdir -p /var/lib/sss/pipes/private;
          chmod 700 /var/lib/sss/pipes/private;
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      containers:
      - name: cavern-sssd
        image: canfar-registry.cloud.computecanada.ca/cadc-sssd:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sssd/sssd.conf
          subPath: sssd.conf
          name: sssd-config-vol
        - mountPath: /etc/openldap/certs/ca.crt
          subPath: ca.crt
          name: sssd-cert-config-vol
        - mountPath: /etc/openldap/certs/cadc_CA_2029.crt
          subPath: cadc_CA_2029.crt
          name: sssd-cert-config-vol
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      - name: "arcade-allocate"
        image: canfar-registry.cloud.computecanada.ca/arcade-allocate:latest
        imagePullPolicy: Always
        # Userid for allocation goes in this argument.
        # TODO: automate the setting of this in the calling script
        command: ["/usr/bin/arcade-cavern-allocate"]
        args: ["cadcauthtest1"]
#        command: [ "/bin/bash", "-c", "--" ]
#        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: "/config"
          name: allocate-config
        - mountPath: /root/.ssl/
          name: servops-cert
          readOnly: true
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: cavern
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      volumes:
      - name: allocate-config
        configMap:
          name: allocate-config
      - name: servops-cert
        secret:
          defaultMode: 420
          secretName: arcade-servops-secret
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim
      - name: sssd-config-vol
        configMap:
          name: sssd-config
          # defaultMode of 256 sets the permissions of the file
          # to 0400 - needed by sssd
          defaultMode: 256
      - name: sssd-cert-config-vol
        configMap:
          name: sssd-cert-config
      - name: sssd-dir
        emptyDir: {}
