swagger: '2.0'
info:
  version: 2.1.0
  title: arcade
  description: |
    ARCADE API Documentation.  This API allows authorized users to create and interact with desktop (NoVNC), CARTA Visualization, and Jupyter Notebook sessions in the arcade processing environment.  Desktop apps can also be launched and attached to arcade desktop sessions through this API.<br/><br/>Clients may authenticate to this service in two ways:<br/>1.  By providing a cookie/token in the Cookie header<br/>2.  By using a client certificate.'
schemes:
  - https
basePath: /arcade
paths:
  /session:
    get:
      description: |
        Get the list of sessions for the requesting user.  Each line represents one session.  Each line is tab-separated into the following columns:<br/><br/>Session ID<br/>Type<br/>Status<br/>Name<br/>Connect URL<br/>StartTime
      tags:
        - Interactive processing
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
      parameters: []
    post:
      description: |
        Launch a new session.
      tags:
        - Interactive processing
      parameters:
        - name: name
          in: query
          type: string
          description: The name for the session.
          required: true
        - name: type
          in: query
          type: string
          description: Type of session, one of 'desktop', 'carta', or 'notebook'
          required: true
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
  /session/{sessionID}:
    delete:
      description: |
        Delete the session identified by sessionID.
      tags:
        - Interactive processing
      parameters:
        - name: sessionID
          in: path
          type: string
          description: The session to delete
          required: true
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
  /session/{sessionID}/app:
    post:
      description: |
        Attach an app to the session identified by sessionID.
      tags:
        - Interactive processing
      parameters:
        - name: sessionID
          in: path
          type: string
          description: The session to delete
          required: true
        - name: software
          in: query
          type: string
          description: The imageID of the app to attach
          required: true
        - name: target-ip
          in: query
          type: string
          description: The IP of the session
          required: true
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
