apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cavern-sshd
  name: cavern-sshd
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cavern-sshd
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cavern-sshd
    spec:
      initContainers:
      - name: init-sssd-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - mkdir /var/lib/sss/pipes/private;
          chmod 700 /var/lib/sss/pipes/private;
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      containers:
      - name: cavern-sshd
        image: canfar-registry.cloud.computecanada.ca/cavern-sshd:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        #command: ["/usr/sbin/sshd", "-D", "-e", "-o", "LogLevel=DEBUG", "-e"]
        ports:
        - containerPort: 22
          protocol: TCP
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-ceph-volume
          subPath: cavern
        - mountPath: /etc/ssh/sshd_config
          name: cavern-sshd-config-vol
          subPath: sshd_config
        - mountPath: /etc/ssh/ssh_host_ecdsa_key.pub
          name: cavern-sshd-config-vol
          subPath: ssh_host_ecdsa_key.pub
        - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
          name: cavern-sshd-config-vol
          subPath: ssh_host_ed25519_key.pub
        - mountPath: /etc/ssh/ssh_host_rsa_key.pub
          name: cavern-sshd-config-vol
          subPath: ssh_host_rsa_key.pub
        - mountPath: /etc/ssh/ssh_host_ecdsa_key
          name: ssh-host-ecdsa-key
          subPath: ssh_host_ecdsa_key
        - mountPath: /etc/ssh/ssh_host_ed25519_key
          name: ssh-host-ed25519-key
          subPath: ssh_host_ed25519_key
        - mountPath: /etc/ssh/ssh_host_rsa_key
          name: ssh-host-rsa-key
          subPath: ssh_host_rsa_key
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      - name: cavern-sssd
        image: canfar-registry.cloud.computecanada.ca/cadc-sssd:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sssd/sssd.conf
          subPath: sssd.conf
          name: sssd-config-vol
        - mountPath: /etc/openldap/certs/ca.crt
          subPath: ca.crt
          name: sssd-cert-config-vol
        - mountPath: /etc/openldap/certs/cadc_CA_2029.crt
          subPath: cadc_CA_2029.crt
          name: sssd-cert-config-vol
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      volumes:
      - name: cavern-ceph-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim-20200608
      - name: cavern-sshd-config-vol
        configMap:
          name: cavern-sshd-config
      - name: ssh-host-ecdsa-key
        secret:
          secretName: cavern-sshd-priv1-secret
          defaultMode: 256
      - name: ssh-host-ed25519-key
        secret:
          secretName: cavern-sshd-priv2-secret
          defaultMode: 256
      - name: ssh-host-rsa-key
        secret:
          secretName: cavern-sshd-priv3-secret
          defaultMode: 256
      - name: sssd-config-vol
        configMap:
          name: sssd-config
          # defaultMode of 256 sets the permissions of the file
          # to 0400 - needed by sssd
          defaultMode: 256
      - name: sssd-cert-config-vol
        configMap:
          name: sssd-cert-config
      - name: sssd-dir
        emptyDir: {}
