---
apiVersion: batch/v1
kind: Job
metadata:
  name: "skaha-allocate"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: "skaha-allocate"
        image: canfar-registry.cloud.computecanada.ca/skaha-allocate:latest
        imagePullPolicy: Always
        # Userid for allocation goes in this argument.
        # TODO: automate the setting of this in the calling script
        command: ["/usr/bin/arcade-cavern-allocate"]
        args: ["cwilson"]
#        command: [ "/bin/bash", "-c", "--" ]
#        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: "/config"
          name: allocate-config
        - mountPath: /root/.ssl/
          name: servops-cert
          readOnly: true
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: cavern
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: allocate-config
        configMap:
          name: allocate-config
      - name: servops-cert
        secret:
          defaultMode: 420
          secretName: skaha-servops-secret
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim-20200608
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
